version: "3.9"
services:

  php:
    build: Docker/php
    ports:
      - '9000:9000'
    container_name: php
    volumes:
      - ./app:/var/www/thn
    depends_on:
      - db
  db:
    platform: linux/x86_64
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secret
    ports:
      - "4306:3306"
  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./app:/var/www/thn
      - ./Docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - db