# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name

    App\Context\Shared\Infrastructure\Bus\Query\MessengerQueryBus: ~
    App\Context\Shared\Application\Bus\Query\QueryBusInterface: '@App\Context\Shared\Infrastructure\Bus\Query\MessengerQueryBus'

    App\:
        resource: '../src/'
        exclude:
            - '../src/Kernel.php'

    App\Tests\Acceptance\:
        resource: '../tests/Acceptance/*'

    App\Tests\Acceptance\Context\Hotel\HotelContext:
        public: true
        arguments:
            - '@App\Context\Hotel\Infrastructure\Write\Information\DoctrineInformationRepository'

    App\Tests\Acceptance\Context\Booking\BookingContext:
        public: true
        arguments:
            - '@App\Context\Booking\Infrastructure\Write\Room\DoctrineRoomRepository'

    App\Tests\Acceptance\Context\Booking\UserContext:
        public: true
        arguments:
            - '@App\Context\Booking\Infrastructure\Write\User\DoctrineUserRepository'


    App\Context\Hotel\Application\Bus\Query\:
        resource: '../src/Context/Hotel/Application/Bus/Query'
        autoconfigure: false
        tags: [{ name: messenger.message_handler, bus: query.bus }]

    App\Context\Booking\Application\Bus\Query\:
        resource: '../src/Context/Booking/Application/Bus/Query'
        autoconfigure: false
        tags: [ { name: messenger.message_handler, bus: query.bus } ]

    App\Context\Hotel\UI\Controller\:
        resource: '../src/Context/Hotel/UI/Controller'
        tags: [ 'controller.service_arguments' ]
        autowire: true

    App\Context\Booking\UI\Controller\:
        resource: '../src/Context/Booking/UI/Controller'
        tags: [ 'controller.service_arguments' ]
        autowire: true

    App\Context\Hotel\Infrastructure\Read\Information\DoctrineInformationRepository:
        arguments:
            - '@doctrine.dbal.default_connection'

    App\Context\Hotel\Infrastructure\Write\Information\DoctrineInformationRepository:
        arguments:
            - '@Doctrine\ORM\EntityManagerInterface'

    App\Context\Booking\Infrastructure\Read\Booking\DoctrineBookingRepository:
        arguments:
            - '@doctrine.dbal.default_connection'
    App\Context\Booking\Infrastructure\Read\Users\DoctrineBookingRepository:
        arguments:
            - '@doctrine.dbal.default_connection'


    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
