doctrine:
    dbal:
        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '13'

        default_connection: default
        connections:
            default:
                # configure these for your database server
                driver: 'pdo_mysql'
                server_version: '8.0.23'
                charset: utf8mb4
                default_table_options:
                    charset: utf8mb4
                    collate: utf8mb4_unicode_ci
                user: '%env(resolve:DB_USERNAME)%'
                password: '%env(resolve:DB_PASSWORD)%'
                host: '%env(resolve:DB_HOST)%'
                port: '3306'
                dbname: '%env(resolve:DB_SCHEMA)%'

            migrations:
                # configure these for your database server
                driver: 'pdo_mysql'
                server_version: '8.0.23'
                charset: utf8mb4
                default_table_options:
                    charset: utf8mb4
                    collate: utf8mb4_unicode_ci
                user: '%env(resolve:DB_USERNAME)%'
                password: '%env(resolve:DB_PASSWORD)%'
                host: '%env(resolve:DB_HOST)%'
                port: '3306'
                dbname: '%env(resolve:DB_SCHEMA)%'
        types:
            uuid: Ramsey\Uuid\Doctrine\UuidType
    orm:
        auto_generate_proxy_classes: true
        entity_managers:
            default:
                mappings:
                    Hotel:
                        is_bundle: false
                        type: xml
                        dir: '%kernel.project_dir%/src/Context/Hotel/Infrastructure/Persistance/Doctrine/Mapping'
                        prefix: 'App\Context\Hotel'
                    Booking:
                        is_bundle: false
                        type: xml
                        dir: '%kernel.project_dir%/src/Context/Booking/Infrastructure/Persistance/Doctrine/Mapping'
                        prefix: 'App\Context\Booking'